# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://dinh.github.io/deck_of_card/"

git_url = "https://github.com/dinh/deck_of_card/tree/{branch}/"

def custom_doc_links(name): return None
